## be sure to use "pod install --no-integrate", which  then requires

platform :osx, '10.7'
source 'https://github.com/CocoaPods/Specs.git'
pod 'CocoaLumberjack'
pod 'FMDB', '~> 2.4'
# pod 'TDOAuth', '~> 1.0.4'
pod 'TDOAuth', :path => '/work/fTDOAuth'
